class Instructions:
    def __init__(self):
        self.instructions = {
            'Harlequin Stitch': [
        {"image": "assets/harlequin/harlequin_diagram.jpg", "text": 'General Diagram \n Chain (CH), Single Crochet (SC) ,Double Crochet (DC)  '},
        {"image": "assets/harlequin/harlequin_start.png", "text": "Start: Chain a multiple of 8 + 2 for the foundation chain. "},
        {"image": "assets/harlequin/harlequin_step1.png", "text": "Step1: SC in 2nd CH from hook and each CH across; turn. "},
        {"image": "assets/harlequin/harlequin_step2.png", "text": "Step 2: CH 1, SC in first STC, skip 3 STS, *(3 DC, CH 1, 3 DC) in next ST, skip 3 ST, SC; repeat from * to end of row; turn. "},
        {"image": "assets/harlequin/harlequin_step2_2.png", "text": "Step 2: CH 1, SC in first STC, skip 3 STS, *(3 DC, CH 1, 3 DC) in next ST, skip 3 ST, SC; repeat from * to end of row; turn. "},
        {"image": "assets/harlequin/harlequin_step3.png", "text": "Step 3: CH 4, DC3TOG in first 3 DC, CH 7, *skip CH-1 space, DC6TOG in next 6 DC (skipping over the center sc), CH 7; repeat from * until 3 DC’s remain, skip CH-1 space, DC3TOG; DC in last SC; turn. "},
        {"image": "assets/harlequin/harlequin_step3_2.png", "text": "Step 3: CH 4, DC3TOG in first 3 DC, CH 7, *skip CH-1 space, DC6TOG in next 6 DC (skipping over the center sc), CH 7; repeat from * until 3 DC’s remain, skip CH-1 space, DC3TOG; DC in last SC; turn. "},
        {"image": "assets/harlequin/harlequin_step4.png", "text": "Step 4: CH 3, make 3 DC in top of DC3TOG from previous row, SC in CH 1 two rows below, catching the CH-7 from row 3, * make (3 DC, CH 1, 3 DC) into next dec ST, SC in CH 1 two rows below, catching the CH-7 from row 3; repeat from * until you reach the last DC3TOG, 3 DC into dc3tog, DC into top of turning CH; turn. "},
        {"image": "assets/harlequin/harlequin_step5.png", "text": "Step 5: CH 4, DC6TOG (skip over the center SC), * CH 7, skip CH-1 space, DC6TOG (skipping over the center SC) repeat from * to end, CH 3, SC into top of turning ch; turn. "},
        {"image": "assets/harlequin/harlequin_step6.png", "text": "Step 6: CH 1, SC in 1st st, make (3 DC, CH 1, 3 DC) into top of next dec ST, *SC in CH-1 space 2 rows below, catching CH-7 in st, make (3 DC, CH 1, 3 DC) into of next dec ST; repeat from * to end, SC in 1st CH of starting ch 4 from prev row; turn. "},

    ],
    'alpine crochet': [
        {"image": "assets/alpine/alpine_diagram.jpg", "text": "General Diagram \n Stitches used: chain (CH), single crochet (SC) ,double crochet (DC) "},
        {"image": "assets/alpine/alpine_step1.png", "text": "Start: Make a foundation chain of even number of stitches – make a slip knot, and go on with chain stitches."},
        {"image": "assets/alpine/alpine_step2.png", "text": "Step 1: Chain 1, single crochet stitches all the way. Remember to work your first single crochet in the first stitch, because turning chain doesn’t count as a stitch here. "},
        {"image": "assets/alpine/alpine_step3.png", "text": "Step 2: chain 3, double crochet stitches all the way.  Remember, that your turning chain (3 chain stitches at the beginning of the row) count as your first stitch. "},
        {"image": "assets/alpine/alpine_step3_2.png", "text": "Step 3: chain 1, single crochet stitches all the way.  Remember about the last stitch of the row, which is worked in the turning chain. "},
        {"image": "assets/alpine/alpine_step4.png", "text": "Step 4: chain 2, *1 fpdc (front post double crochet) in the double crochet of row 2, 1 double crochet*, until you reach last stitch, which is 2 double crochets. Remember to always skip one stitch “behind” fpdc, when working your dc’s, so that stitch count stays the same.  "},
        {"image": "assets/alpine/alpine_step4_2.png", "text": "Step 4: chain 2, *1 fpdc (front post double crochet) in the double crochet of row 2, 1 double crochet*, until you reach last stitch, which is 2 double crochets. Remember to always skip one stitch “behind” fpdc, when working your dc’s, so that stitch count stays the same.  "},
        {"image": "assets/alpine/alpine_step5.png", "text": "Step 5: chain 1, single crochet stitches all the way.  "},
        {"image": "assets/alpine/alpine_step6.png", "text": "Step 6: chain 2, *1 double crochet, 1 fpdc (front post double crochet) in the double crochet of row 4*; your last stitch should be 1 double crochet. "},
        {"image": "assets/alpine/alpine_step6_2.png", "text": "Step 6: chain 2, *1 double crochet, 1 fpdc (front post double crochet) in the double crochet of row 4*; your last stitch should be 1 double crochet. "},
        {"image": "assets/alpine/alpine_step7.png", "text": "Step 7: chain 1, single crochet stitches all the way "},
    ],
    'basket weave crochet stitch': [
        {"image": "assets/basket/basket_step_diagram.PNG", "text": "General Diagram \n CH: chain DC: double crochet FPDC: front post double crochet  BPDC: back post double crochet "},
        {"image": "assets/basket/basket_step_diagram.PNG", "text": "Start: This stitch is done using a multiple of 6 stitches plus 4. Our swatch started with 16 stitches and used worsted weight yarn."},
        {"image": "assets/basket/basket_step1.PNG", "text": "Step 1: DC in the 4th chain from hook, DC in all chain sts across. When you get to the end of your row, CH 2 and turn. "},
        {"image": "assets/basket/basket_step2.PNG", "text": "Step 2: Skip the first DC, *FPDC in next 3 sts, BPDC in next 3 sts; repeat from * to the end of your row, DC in top chain of turning chain from the row below, CH 2, turn. "},
        {"image": "assets/basket/basket_step3.PNG", "text": "Step 3: Repeat row 2. "},
        {"image": "assets/basket/basket_step4.PNG", "text": "Step 4: Skip first DC, *3 BPDC, 3 FPDC; repeat from * to end, DC in top CH of turning CH from row below, CH 2, turn. "},
        {"image": "assets/basket/basket_step5.PNG", "text": "Step 5: Repeat Row 4. "}
    ],
    'feather stitch': [
        {"image": "assets/feather/feather_diagram.jpg", "text": "General Diagram \n CH = Chain ,HDC = Half double crochet  FHDC  = Foundation half double crochet  CH SP = Chain space   ST = Stitch "},
        {"image": "assets/feather/feather_diagram.jpg", "text": "Start:  Start with a chain using an odd number of stitches. Stitch multiple is 2 + 3. Each “feather” is the width of two chains.  The CH-1 at the beginning of the row does NOT count as a stitch. "},
        {"image": "assets/feather/feather_step1and2.jpg", "text": "Step 1:  1. Chain an odd number of stitches. Half double crochet in the third chain from the hook. "},
        {"image": "assets/feather/feather_step2and2.jpg", "text": "Step 2: Chain one, skip the next chain and half double crochet in the next. << repeat this step to the end of the row. "},
        {"image": "assets/feather/feather_step3.jpg", "text": "Step 3: To start the next row, chain one and turn. Half double crochet in the first stitch, and then chain one. "},
        {"image": "assets/feather/feather_step4.PNG", "text": "Step 4:  To make a feather stitch: * Yarn over pull up a loop in the chain-space. (3 loops on hook)  "},
        {"image": "assets/feather/feather_step4_2.PNG", "text": "Yarn over and pull up a loop in the skipped chain directly below (from the beginning chain). "},
        {"image": "assets/feather/feather_step4_3.PNG", "text": " (5 loops on hook) Yarn over and pull up a loop in the next chain-space. "},
        {"image": "assets/feather/feather_step4_4.PNG", "text": " (7 loops on hook) Yarn over and pull through all 7 loops.  "},
        {"image": "assets/feather/feather_step4_5.PNG", "text": "Chain one to close the stitch. Feather stitch made! "},
        {"image": "assets/feather/feather_step5.PNG", "text": "Step 5: 5. Repeat step 4 to the end of the row. When you get there, half double crochet in the last stitch. (don’t forget the chain one to close the final feather) "},
        {"image": "assets/feather/feather_step5_1.PNG", "text": "Step 5: 5. Repeat step 4 to the end of the row. When you get there, half double crochet in the last stitch. (don’t forget the chain one to close the final feather) "},
        {"image": "assets/feather/feather_step6.PNG", "text": "Step 6: 6. Chain one and turn. Half double crochet in the first stitch, and then chain one. "},
        {"image": "assets/feather/feather_step6_1.PNG", "text": "Step 6: Yarn over pull up a loop in the chain-space. (3 loops on hook) Yarn over and pull up a loop in the chain-space from the previous row. (5 loops on hook) Yarn over and pull up a loop in the next chain-space. (7 loops on hook) Yarn over and pull through all 7 loops. Chain one to close the stitch. * Repeat from the first asterisk to the end of the row. When you get there, half double crochet in the last stitch. (don’t forget the chain one to close the final feather) "},
        {"image": "assets/feather/feather_step7.PNG", "text": "Repeat step 6 until the piece is as tall as you like. That’s it!"},
    ],
    'herringbone crochet': [
        {"image": "assets/herringbone/HB_diagram.jpg", "text": " General Diagram \n Stitches ch: chain(s) hsc: herringbone single crochet rhsc: reverse herringbone single crochet sc: single crochet st(s): stitch(es) "},
        {"image": "assets/herringbone/HB_start.png", "text": "Start: Foundation chain: Start with any number of stitches (chains). "},
        {"image": "assets/herringbone/HB_step1.png", "text": "Step 1: Right side. Work regular single crochet in the 2nd ch from the hook working in the back bump of the chain. The needle points at the right place. "},
        {"image": "assets/herringbone/HB_step1_2.png", "text": "Step 1: Right side. Work regular single crochet in the 2nd ch from the hook working in the back bump of the chain. The needle points at the right place. "},
        {"image": "assets/herringbone/HB_step2.png", "text": "Step 2: Next, insert hook into left leg of sc just made. "},
        {"image": "assets/herringbone/HB_step3.png", "text": "Step 3: Now, insert the hook into the back bump of the next chain and pull up a first loop, yarn over and pull through all three loops on the hook. "},
        {"image": "assets/herringbone/HB_step3_2.png", "text": "Step 3 countinues"},
        {"image": "assets/herringbone/HB_step3_3.png", "text": "Step 3 countinues"},
        {"image": "assets/herringbone/HB_step4.png", "text": "Step 4: Continue working herringbone single crochet to end. First, insert your hook into left leg of previous stitch, then insert the hook into the back bump of the next chain. Pull up a loop, yarn over and pull through all three loops on the hook. Turn. "},
        {"image": "assets/herringbone/HB_step4_2.png", "text": "Step 4 countinues"},
        {"image": "assets/herringbone/HB_step5.png", "text": "Step 5: Wrong Side of Your Work. Countinues "},
        {"image": "assets/herringbone/HB_step5_2.png", "text": " Chain 1 (turning chain, do not count as a stitch). Work single crochet in first stitch from the back to the front (the needle points the right direction). "},
        {"image": "assets/herringbone/HB_step5_3.png", "text": "Step 5 countinues"},
        {"image": "assets/herringbone/HB_step5_4.png", "text": "Step 5 countinues"},
        {"image": "assets/herringbone/HB_step5_5.png", "text": "Step 5 countinues"},
        {"image": "assets/herringbone/HB_step6.png", "text": "Step 6: To work a next stitch, insert the hook into left strand of the previous stitch (from right to left) and then insert the hook into the next stitch working from back to front. Yarn over, pull up a loop, yarn over and pull through all three loops on the hook. "},
        {"image": "assets/herringbone/HB_step6_1.png", "text": "Step 6 countinues"},
        {"image": "assets/herringbone/HB_step6_2.png", "text": "Step 6 countinues"},
        {"image": "assets/herringbone/HB_step6_3.png", "text": "Step 6 countinues"},
        {"image": "assets/herringbone/HB_step6_4.png", "text": "Step 6 countinues"},
        {"image": "assets/herringbone/HB_step7.png", "text": "Step 7: Work in the same manner to the end of the row. "},
        {"image": "assets/herringbone/HB_step8.png", "text": "Step 8: Right Side. Chain 1 (turning chain, do not count as a stitch). Work single crochet in 1st stitch from the front to back. "},
        {"image": "assets/herringbone/HB_step9.png", "text": "Step 9: To work a next stitch, insert the hook into left strand of the previous stitch (from right to left) and then insert the hook into the next stitch working from front to back. Yarn over, pull up a loop, yarn over and pull through all three loops on the hook. "},
        {"image": "assets/herringbone/HB_step9_1.png", "text": "Step 9 countinues"},
        {"image": "assets/herringbone/HB_step9_2.png", "text": "Step 9 countinues"},
        {"image": "assets/herringbone/HB_step9_3.png", "text": "Work in the same manner to the end of the row. "}
    ],

    'jasmine crochet': [
        {"image": "assets/jasmine/jasmine_diagram.PNG", "text": "General Diagram \n Stitches Chain – ch Foundation Puff Stitch – fps Jasmine Stitch – js  "},
        {"image": "assets/jasmine/jasmine_diagram.PNG", "text": "Start :  Start by making 2 foundation chains. Then, pull out the loop on your hook to about a half inch. Next step is to make foundation puff stitch. "},
        {"image": "assets/jasmine/puff_1.PNG", "text": "Yarn over. 2 loops on hook."},
        {"image": "assets/jasmine/puff_2.PNG", "text": "Insert hook into same chain, yarn over, draw up a loop, and yarn over.  "},
        {"image": "assets/jasmine/puff_3.PNG", "text": "Repeat this step until there are 8 loops on your hook (the last YO counts as a loop!)"},
        {"image": "assets/jasmine/puff_4.PNG", "text": " Using your thumb and middle finger, hold the back of the last loop on your hook."},
        {"image": "assets/jasmine/puff_5.PNG", "text": "Draw the last loop through all loops on hook while still holding that strand from the last step."},
        {"image": "assets/jasmine/puff_6.PNG", "text": "Single crochet into the loop you are holding with your middle finger. Ch 1."},
        {"image": "assets/jasmine/puff_7.PNG", "text": "That is one foundation puff stitch.   "},
        {"image": "assets/jasmine/puff_8.PNG", "text": "Here is what a row of foundation puff stitches should look like. Do as much as you want"},
        {"image": "assets/jasmine/jasmine_step1.PNG", "text": "Step 1: Begin making another puff stitch, but don’t draw the last loop through to finish off the stitch. Keep all 8 loops on your hook. Next, insert the hook here and draw up a loop, and continue making a puff stitch here. "},
        {"image": "assets/jasmine/jasmine_step2.PNG", "text": "Step 2: Again, don’t draw the last loop through. You should now have 16 loops on your hook. Repeat one last time in the next chain stitch. "},
        {"image": "assets/jasmine/jasmine_step3.PNG", "text": "Step 3: You should now have 24 loops on your hook.   "},
        {"image": "assets/jasmine/jasmine_step4.PNG", "text": "Step 4: Now, finish off the Jasmine stitch bit holding the back of the last loop, and drawing it through ALL 24 loops. Still hold back that strand from the YO as you do this! "},
        {"image": "assets/jasmine/jasmine_step5.PNG", "text": "Step 5: Now make a single crochet with the loop on your hook and back end of that same loop which should still be held by your left hand.   "},
        {"image": "assets/jasmine/jasmine_step6.PNG", "text": "Step 6: Ch 1. And that’s your first Jasmine stitch! "},
        {"image": "assets/jasmine/jasmine_step7.PNG", "text": "Step 7: The rest of them work exactly the same way, only the place you insert your hook looks a little different because it’s not a flat row anymore. The second 8 loops will go here. (Where the hook is pointing.) "},
        {"image": "assets/jasmine/jasmine_step8.PNG", "text": "Step 8: And the third set of 8 stitches will go here. (The following chain stitch.) "},
        {"image": "assets/jasmine/jasmine_step9.PNG", "text": "Step 9: Continue working your Jasmine stitches to the end of the row. "},
        {"image": "assets/jasmine/jasmine_step9_1.PNG", "text": "Every row from now on will be worked like this.  "}
    ],

    'moss crochet': [
        {"image": "assets/moss/moss_diagram.PNG", "text": "General Diagram \n Stitches: st – Stitch ,sc - Single crochet , ch – Chain ,ch-sp - Chain space "},
        {"image": "assets/moss/moss_diagram.PNG", "text": "Start : Make a foundation chain with an even number of chain stitches, and work as follows. "},
        {"image": "assets/moss/moss_step1.PNG", "text": "Step 1:  1sc in second ch from hook, * ch1, miss next ch, 1sc in next ch * repeat from * to end, then turn.  You should have half as many sc as you had in your starting chain, plus one. "},
        {"image": "assets/moss/moss_step2.PNG", "text": "Step 2: 2nd row: ch1 (doesn’t count as a st), 1sc in first st, 1sc in ch-sp, ch1, *miss next sc, 1sc in ch-sp, ch1*, to last st, 1sc, turn.   "},
        {"image": "assets/moss/moss_step3.PNG", "text": "Step 3: ch1 (doesn’t count as a st), 1sc in first st, *ch1, miss next sc, 1sc in ch-sp* to last 2 sts, ch 1, miss next st, 1sc in last st, turn. "},
        {"image": "assets/moss/moss_step3_1.PNG", "text": "Step 3_1: Repeat the 2nd and 3rd rows to create your moss stitch pattern. "},
        {"image": "assets/moss/moss_step4.PNG", "text": "Do it as much as you want!"}
    ],
    'shell crochet': [
        {"image": "assets/shell/shell_diagram.PNG", "text": "General Diagram \n Stitches:ch = chain stitch,dc = double crochet stitch sc = single crochet stitch,st/sts = stitch/es  "},
        {"image": "assets/shell/shell_start.PNG", "text": "Start: Chain a multiple of six stitches plus two. To follow along with my swatch, use a starting chain of 26. (Here’s the math: 4 x 6 + 2, which will give us a swatch that’s four shells wide .) "},
        {"image": "assets/shell/shell_step1.PNG", "text": "Step 1: Sc into the 2nd chain from the hook. "},
        {"image": "assets/shell/shell_step1_1.PNG", "text": "Step 2: Skip the next two chains, then work 5 dc into the next chain. "},
        {"image": "assets/shell/shell_step1_2.PNG", "text": "Step 3: Skip the next 2 chains, then sc into the next chain. Repeat from * across the row. "},
        {"image": "assets/shell/shell_step1_3.PNG", "text": "Step 4: The last stitch should be a sc into the last ch. Turn."},
        {"image": "assets/shell/shell_step2.PNG", "text": "Step 5: Ch 3 (counts as a dc here and throughout.) 2 dc into the first st. (The turning chain plus the 2 dc form a half shell.) "},
        {"image": "assets/shell/shell_step2_1.PNG", "text": "Step 6:  Skip 2 sts, and sc into the next dc. (If everything is lined up correctly, you should be working the sc into the center dc from the group of shell stitches in the previous row.)  "},
        {"image": "assets/shell/shell_step2_2.PNG", "text": "Step 7:  Skip 2 sts, and 5 dc into the next sc. (You should be working the 5 dc into the sc in the row below.)"},
        {"image": "assets/shell/shell_step2_3.PNG", "text": "Step 8:  Repeat from * across the row, until you get to the last 3 stitches. Skip 2 sts, and work 3 dc into the last sc (This forms another half shell.) Turn."},
        {"image": "assets/shell/shell_step3.PNG", "text": "Step 9: Row 3 is very similar to Row 1. One thing to watch out for, here: the last sc will be made into the top of the turning chain from the previous row. Repeat Row 2 and Row 3 until you reach the desired length for your crochet shell stitch swatch."}
    ],
    'star stitch': [
        {"image": "assets/star/star_diagram.PNG", "text": "General Diagram \n Stitches: ch = chain, hdc = half double crochet  "},
        {"image": "assets/star/star_step1.PNG", "text": "Step1 : Make the Foundation Chain begin with an odd number of chain stitches. Insert your hook into the second chain from the hook. Yarn over and pull a loop through. This is the beginning of a single crochet stitch, but instead of completing the entire stitch, leave the loop on the hook. "},
        {"image": "assets/star/star_step2.PNG", "text": "Step 2: Insert your hook into the next chain, yarn over and pull through. There are now three loops on the hook. Continue to insert your hook into subsequent chains, yarning over and pulling through until there are six loops on your hook. "},
        {"image": "assets/star/star_step3.PNG", "text": "Step 3:  With six loops on your hook, yarn over one more time and pull through all six loops. The loops create the spikes that make up your first star. "},
        {"image": "assets/star/star_step4.PNG", "text": "Step 4: Chain one. This finishes the star. It also creates an eye in the center of the star. You will work into the eye, so it's helpful to get a feel for the stitch design.  "},
        {"image": "assets/star/star_step5.PNG", "text": "Step 5: Next, insert your hook into the eye that you just made. Yarn over and pull through. There will now be two loops on your hook. "},
        {"image": "assets/star/star_step6.PNG", "text": "Step 6: Insert your hook into the space between the two last spikes from the first star. Yarn over and pull through. There will be three loops on your hook. Placement is everything with the crochet star stitch, so pay careful attention to where you are inserting the hook at each step. "},
        {"image": "assets/star/star_step7.PNG", "text": "Step 7: Insert your hook into the same chain where you worked the last stitch of the previous star. Yarn over and pull through. There will now be four loops on your hook. Insert your hook into the next chain, yarn over and pull through. Repeat in the next chain. This will give you six loops on your hook. "},
        {"image": "assets/star/star_step8.PNG", "text": "Step 8: Finish this second star as you did the first one. Yarn over and pull through all six loops on the hook. Chain one to close the second star. "},
        {"image": "assets/star/star_step9.PNG", "text": "Step 9: Repeat the steps above to make stars all the way across the row. When you get to the end, make one hdc in the last stitch. "},
        {"image": "assets/star/star_step10.PNG", "text": "Step 10: Between each row of star stitches, work rows of hdc stitches. Turn the work and chain 2. This counts as the first hdc stitch of the row. Crochet two hdc stitches into the eye of the star in the row below. "},
        {"image": "assets/star/star_step11.PNG", "text": "Step 11: Work 2 hdc in the eye of each star across the row. When you get to the end, crochet 2 hdc in the final stitch. "},
        {"image": "assets/star/star_step12.PNG", "text": "Step 12: To make another row of crochet stars, the process is almost the same as before, except that it begins with extra chain stitches. Turn the work and chain three. Insert your hook into the second chain from the hook. Yarn over and pull through. There will now be two loops on the hook. Insert your hook into the next chain, then yarn over and pull through. There will now be three loops on the hook. "},
        {"image": "assets/star/star_step13.PNG", "text": "Step 13: Insert your hook into each of the next three stitches, doing a yarn over and pull through in each so that you have six stitches on the hook. Yarn over and pull through all six loops on the hook. Chain one to close the star. This creates the eye of the first star of this row (which is the third row of the pattern and the second of the star stitch rows). "},
        {"image": "assets/star/star_step14.PNG", "text": "Step 14: Finish the row of start stitch, then work another row of hdc, and so on. Work the crochet star stitch on odd number rows and half double crochet stitches on even-numbered rows. "},

    ],
    'waffle stitch': [
        {"image": "assets/waffle/waffle_diagram.PNG", "text": "General Diagram \n Stitches: dc(s) = double crochet(s) st(s) = stitch(es) ch(s) = chain(s) fpdc(s) = front post double crochet(s) "},
        {"image": "assets/waffle/waffle_step1.PNG", "text": "Step 1: Ch 11. (a multiple of 3 + 2 sts)"},
        {"image": "assets/waffle/waffle_step2.PNG", "text": "Step 2: Row 1 Locate the 4th ch from the hook."},
        {"image": "assets/waffle/waffle_step3.PNG", "text": "Step 3: Dc into the fourth ch from the hook"},
        {"image": "assets/waffle/waffle_step4.PNG", "text": "Step 4:Double crochet (dc) into each of the remaining chs in the row"},
        {"image": "assets/waffle/waffle_step5.PNG", "text": "Step 5:Turn the work, ch 2 and locate the next st to fpdc around."},
        {"image": "assets/waffle/waffle_step6.PNG", "text": "Step 6:Fpdc around the stitch"},
        {"image": "assets/waffle/waffle_step7.PNG", "text": "Step 7:Dc into the next st"},
        {"image": "assets/waffle/waffle_step8.PNG", "text": "Step 8:Dc into the next st"},
        {"image": "assets/waffle/waffle_step9.PNG", "text": "Step 9:Fpdc around the next st"},
        {"image": "assets/waffle/waffle_step10.PNG", "text": "Step 10:Dc once into each of the next two sts"},
        {"image": "assets/waffle/waffle_step11.PNG", "text": "Step 11:fpdc around the next st"},
        {"image": "assets/waffle/waffle_step12.PNG", "text": "Step 12: Locate the turning ch"},
        {"image": "assets/waffle/waffle_step13.PNG", "text": "Step 13: Dc into the top of the turning ch (9 total sts across the row)"},
        {"image": "assets/waffle/waffle_step14.PNG", "text": "Step 14:Turn the work, ch 2"},
        {"image": "assets/waffle/waffle_step15.PNG", "text": "Step 15:dc in the next stitch, fpdc around each of the next two sts"},
        {"image": "assets/waffle/waffle_step16.PNG", "text": "Step 16:dc in the next stitch, fpdc around each of the next two sts"},
        {"image": "assets/waffle/waffle_step17.PNG", "text": "Step 17:dc in the next stitch"},
        {"image": "assets/waffle/waffle_step18.PNG", "text": "Step 18:Dc into the top of the turning ch."},
        {"image": "assets/waffle/waffle_step19.PNG", "text": "Step 19:Rep rows 2 + 3 for to the desired length of the pattern or crochet project. You will see the waffle stitch start to form with the row repeat. "},
    ]

        }

    def get_instructions(self, predicted_label):
        return self.instructions.get(predicted_label, []);
